version: "3.9"

services:
  postgres:
    image: postgres:15.3-alpine
    container_name: tc-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  tc-backend:
    depends_on:
      postgres:
        condition: service_healthy
    image: tc-backend
    build: .
    ports:
      - 8080:8080
    restart: always
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASS: ${POSTGRES_PASSWORD}
      DATABASE_PORT: 5432
      DATABASE_NAME: ${POSTGRES_DB}

volumes:
  pgdata:
    external: false