# Server Configuration
server:
  port: 8080
  undertow:
    threads:
      worker: 30
  session:
    persistent: false # performance
    store-dir: /var/log/app # performance

# Pool Connection and Postgres settings
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    date-format: yyyy-MM-dd
  
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
  profiles:
    active: local
  application:
    name: tc-backend-api

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASS:123456}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      pool-name: TcBackendApiPool
      idle-timeout: 9000
      #isolate-internal-queries: true
      connection-test-query: SELECT 1
      connection-timeout: 18000
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
        enable_lazy_load_no_trans: true
    open-in-view: false


app:
  cache.user.token: true
  mvc.async.request-timeout: 10000
  thread.async:
    corePoolSize: 20
    maxPoolSize: 300
    queueCapacity: 600
  client:
    name: tc_client
    secret: $2a$12$aNBFov6o75DX51iVqd5mM.Z5S.Wi7xHMS3OzcU5386TWRi28Y691W
    signKey: tech-challenge
    tokenExpirationTime: 86400
    refreshTokenExpirationTime: 86400
  config:
    upload:
      mimeTypes: data:image/png;base64, data:image/jpg;base64
      #mimeTypes: data:image/jpg;base64, data:image/xpto;base64
      maxLength: 1024000
      #maxLength: 200000
      maxProductImages: 5

