apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tc-backend-s2-dep
  namespace: fiap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-tc-backend-s2
  template:
    metadata:
      labels:
        app: app-tc-backend-s2
    spec:
      containers:
        - name: app-tc-backend-s2
          image: 'jcmds/fiap-8soat-tc:latest'
          ports:
            - name: http 
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/public/v1/health
              port: 8080
            failureThreshold: 1
            periodSeconds: 15           
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: DATABASE_HOST
              value: db-tc-backends2-fiap.cqjmd1nvleyg.us-east-1.rds.amazonaws.com
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: credentials-rds
                  key: username
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: credentials-rds
                  key: password
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: postgres
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%                 
        
        


 