apiVersion: v1
kind: Service
metadata:
  name: app-tc-backend-s2-svc
  namespace: fiap
spec:
  selector:
    app: app-tc-backend-s2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
